description: "Unique identifier of the benefit type.<p>Must conform to the regular expression</p><p>`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`</p>"
type: string
example: "123e4567-e89b-12d3-a456-426614174000"