is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.formatValue
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearNotEnded
  - errors.ruleIncorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Amend State Benefit Amounts [test only]
description: 'This endpoint allows a developer to create/update benefits financial data. A National Insurance number, tax year and benefit ID must be provided.'
(annotations.sandboxData): !include ../scenarios/common.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/amend_benefitAmounts_request.json
    example: !include ../examples/amendBenefitAmounts/request.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/amend_benefitAmounts_response.json
        example: !include ../examples/amendBenefitAmounts/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.