is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.formatStartDate
  - errors.formatEndDate
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearNotEnded
  - errors.ruleEndDateBeforeStartDate
  - errors.ruleStartDateAfterTaxYearEnd
  - errors.ruleEndDateBeforeTaxYearStart
  - errors.ruleUpdateForbidden
  - errors.ruleIncorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Amend State Benefit [test only]
description: 'This endpoint allows a developer to amend a previously created customer benefit, if the customer attempts to update a HMRC held benefit then this operation will fail with a forbidden response code. A National Insurance number, tax year and benefit ID must be provided.<br><br>This endpoint can only be used for a tax year that has ended.'
(annotations.sandboxData): !include ../scenarios/amendBenefit.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/amend_benefit_request.json
    example: !include ../examples/amendBenefit/request.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/amend_benefit_response.json
        example: !include ../examples/amendBenefit/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.