is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.formatValue
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearNotEnded
  - errors.ruleIncorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Create and Amend State Benefit Amounts
description: 'This endpoint allows a developer to create or amend state benefit amounts.<br><br>Where the benefit ID relates to a customer created state benefit, the amount values will updated.<br><br>Where the benefit ID relates a HMRC held benefit, this will result in a duplicate benefit being created within the `customerAddedStateBenefits` array with the updated amount values. It will have the same benefit ID.<br><br>Where a duplicate benefit exists the benefit with the most recent `submittedOndate` will be used - older values will be ignored.<br><br>A National Insurance number, a tax year, a benefit type and start date must be provided.<br><br>This endpoint can only be used within the current tax year for `employmentSupportAllowance` and `jobSeekersAllowance` benefit types.'
(annotations.sandboxData): !include ../scenarios/amendBenefitAmounts.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include ../schemas/amend_benefitAmounts_request.json
    example: !include ../examples/amendBenefitAmounts/request.json
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/amend_benefitAmounts_response.json
        example: !include ../examples/amendBenefitAmounts/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.