is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.ruleDeleteForbidden
displayName: Delete State Benefit [test only]
description: 'This endpoint allows a developer to delete customer submitted state benefits. If the customer attempts to delete a HMRC held state benefit then the operation will fail with a forbidden response. A National Insurance number, tax year and benefit ID must be provided.<br><br>This endpoint can only be used for a tax year that has ended.'
(annotations.sandboxData): !include ../scenarios/deleteBenefit.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  204:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters