is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearNotEnded
  - errors.ruleUnignoreForbidden
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Unignore State Benefit [test only]
description: 'This endpoint allows a customer to mark a State Benefit as unignored, customer added benefits can’t be unignored they can only be deleted. A National Insurance number, tax year and benefit ID must be provided.'
(annotations.sandboxData): !include ../scenarios/unignoreBenefit.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/unignore_response.json
        example: !include ../examples/unignoreBenefit/response.json
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.