#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: 'The supplied income source could not be found.'
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  ruleIncorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIncorrectOrEmptyBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied tax year field is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  formatBenefitId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatBenefitId:
                description: 'The format of the supplied benefit ID field is not valid.'
                value:
                  code: FORMAT_BENEFIT_ID
  formatBenefitType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatBenefitType:
                description: 'The format or value of benefit type is not valid.'
                value:
                  code: FORMAT_BENEFIT_TYPE
  formatStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatStartDate:
                description: 'The format of the supplied start date is not valid.'
                value:
                  code: FORMAT_START_DATE
  formatEndDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEndDate:
                description: 'The format of the supplied end date is not valid.'
                value:
                 code: FORMAT_END_DATE
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: 'One or more values have been added with the incorrect format.'
                value:
                  code: FORMAT_VALUE
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  ruleTaxYearNotEnded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearNotEnded:
                description: 'The submission has been made before the tax year it relates to has ended.'
                value:
                  code: RULE_TAX_YEAR_NOT_ENDED
  ruleEndDateBeforeStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleEndDateBeforeStartDate:
                description: 'The end date is earlier than the start date.'
                value:
                  code: RULE_END_DATE_BEFORE_START_DATE
  ruleStartDateAfterTaxYearEnd:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleStartDateAfterTaxYearEnd:
                description: 'The benefit is listed as starting after the tax year ended.'
                value:
                  code: RULE_START_DATE_AFTER_TAX_YEAR_END
  ruleEndDateBeforeTaxYearStart:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleEndDateBeforeTaxYearStart:
                description: 'The benefit is listed as ending before the tax year began.'
                value:
                  code: RULE_END_DATE_BEFORE_TAX_YEAR_START
  ruleUpdateForbidden:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleUpdateForbidden:
                description: 'An update for a HMRC held benefit is not permitted.'
                value:
                  code: RULE_UPDATE_FORBIDDEN
  ruleDeleteForbidden:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleUpdateForbidden:
                description: 'A deletion for a HMRC held state benefit is not permitted.'
                value:
                  code: RULE_DELETE_FORBIDDEN
  ruleIgnoreForbidden:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIgnoreForbidden:
                description: 'The remote endpoint has indicated that State Benefit cannot be ignored.'
                value:
                  code: RULE_IGNORE_FORBIDDEN