#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  benefitId:
    queryParameters:
      benefitId:
        description: "Unique identifier of the benefit."
        example: "f0d83ac0-a10a-4d57-9e41-6d033832779f"
        required: false